version: 2

sources:
 - name: raw
   schema: gz_raw_data
   tables:
    - name: sales
      identifier: raw_gz_sales
      description: sales data for greenweez
      columns:
        - name: date_date
          description:  date of orders
        - name: orders_id
          description: foreign key to ship
        - name: pdt_id
          description: foreign key to product
        - name: reveneu
          description: the amount paid by the customer to pruchase the product
        - name: quantity
    - name: product
      identifier: raw_gz_product
      columns:
        - name: products_id
          description: primary key
          tests:
            - unique
            - not_null
        - name: purchase_price
          description: the pruchase price of products
    - name: ship
      identifier: raw_gz_ship
      columns:
        - name: orders_id
          description:  primary key
          tests:
            - unique
            - not_null
        - name: shipping_fee
          description: the price of the customer pays for shipping
        - name: log_cost
        - name: ship_cost 
